[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "CodeLess"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true }
rfd = "0.14"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]

