[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[features]
mobile = []

[dependencies]
anyhow = "1.0.99"
dioxus = { workspace = true }
serde = "1.0.219"
serde_json = "1.0.143"

# Web-specific dependencies (conditionally compiled)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "console",
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "FileReader",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlAnchorElement",
  "File",
  "FileList",
  "Blob",
  "Url",
  "Window",
  "HtmlBodyElement",
] }
js-sys = "0.3"
futures-channel = "0.3"
